Implementation of Channel methods for core/db
revoltchat/backend pull request #244
Opened 2023-05-16 03:11 UTC by toastxc

## Please make sure to check the following tasks before opening and submitting a PR

* [x] I understand and have followed the [contribution guide](https://github.com/revoltchat/revolt/discussions/282)
* [ ] I have tested my changes locally and they are working as intended
* [ ] These changes do not have any notable side effects on other Revolt projects

2023-05-23 20:49 UTC, insertish requested changes
Presuming the actual queries work fine, we'll be writing tests anyways so it's not a huge concern as long as it looks ok.

2023-05-23 20:49 UTC, insertish commented on crates/core/database/src/models/channels/model.rs
> +    pub struct NullName {
Is it possible to drop the public modifier here?

2023-05-23 20:49 UTC, insertish commented on crates/core/database/src/models/channels/model.rs
> +impl Channel {
I would re-order the methods here to be in the order of C-R-U-D.
Create, Read, Update, Delete

I've been doing this to make it easier to consistently navigate through the models

2023-05-23 20:49 UTC, insertish commented on crates/core/database/src/models/channels/ops.rs
> +pub trait AbstractChannels: Sync + Send {
Also re-order here and in implementations

2023-05-23 20:49 UTC, insertish commented on crates/core/permissions/Cargo.toml
> +bson = { version = "2.1.0" }
This should be feature flagged

2023-05-23 20:49 UTC, insertish commented on crates/core/permissions/Cargo.toml
> +revolt_rocket_okapi = { version = "0.9.1", features = [ "swagger" ] }
This is not necessary as schemars is already available behind a feature flag

2023-05-23 20:49 UTC, insertish commented on crates/core/permissions/Cargo.toml
> +rocket = { version = "0.5.0-rc.2", default-features = false, features = ["json"] }
Is this used anywhere?

2023-05-23 20:49 UTC, insertish commented on crates/core/permissions/src/models/server.rs
> +use revolt_rocket_okapi::{revolt_okapi::schemars, JsonSchema};
Use
```rust
#[cfg_attr(feature = "schemars", derive(JsonSchema))]
```

However, it is necessary to add these 3 lines to lib.rs: https://github.com/revoltchat/backend/blob/master/crates/core/models/src/lib.rs#L5

2023-05-23 20:49 UTC, insertish commented on crates/core/permissions/src/models/server.rs
> +impl From<OverrideField> for Bson {
Feature flag here after bson is changed in dependencies

2023-05-23 20:49 UTC, insertish commented on crates/quark/src/util/variables/delta.rs
> +pub static MAX_BOT_COUNT: Lazy<usize> = Lazy::new(|| env::var("REVOLT_MAX_BOT_COUNT").unwrap_or_else(|_| "5".to_string()).parse().unwrap());
This seems to revert another PR.

2023-05-23 20:49 UTC, insertish commented on crates/core/database/src/models/channels/ops/mongodb.rs
> +            .update_one(user_doc, group_doc, None)
You can put the `doc! {}` macro straight into the method parameters, this is how I've been doing it so far on the other collections.

2023-05-25 06:07 UTC, toastxc commented
I believe all of the requests changes have been implemented ^w^

2023-05-27 11:43 UTC, toastxc commented
sorry I don't think I used the change request feature properly, but all the changes should be ok

2023-05-31 16:18 UTC, insertish requested changes
Looks almost ready for merge, found a few more things

2023-05-31 16:18 UTC, insertish commented on crates/core/database/src/models/channels/ops/mongodb.rs
> +
extraneous newline

2023-05-31 16:18 UTC, insertish commented on crates/core/database/src/models/channels/ops/reference.rs
> +#![allow(warnings)]
probably shouldn't be here

2023-05-31 16:18 UTC, insertish commented on crates/core/database/src/models/channels/ops/reference.rs
> +static COL: &str = "channels";
This line can be omitted here.

2023-05-31 16:18 UTC, insertish commented on crates/core/database/src/models/channels/ops/reference.rs
> +        todo!()
impl

2023-05-31 16:18 UTC, insertish commented on crates/core/database/src/models/channels/ops/reference.rs
> +        todo!()
impl

2023-05-31 16:18 UTC, insertish commented on crates/delta/src/routes/servers/permissions_set_default.rs
>  #[openapi(tag = "Server Permissions")]
Route description removed by accident

2023-06-01 02:19 UTC, toastxc commented
There was a conflict, earlier I added Channel as a dependancy for the DB MutexGuard.

2023-06-03 12:13 UTC, insertish commented
Webhooks just got merged, now conflicting, should be fairly quick to fix.

2023-06-03 14:54 UTC, closed without merging